#!/bin/bash

#DEBHELPER#

# postinst script for lightdm-modified-init

#set -e

case "$1" in
  install|upgrade|configure) update-rc.d sddm remove
                   update-rc.d sddm defaults
                   update-rc.d oosddm remove
                   #update-rc.d oosddm defaults
                   ;;

                *) :
                   ;;
esac 

exit 0
