#!/bin/bash

#DEBHELPER#

# postinst script for sddm-modified-init

#set -e

case "$1" in
  install|upgrade|configure) 
                   #copy in if removed by something else debian does
                   if [ ! -e /etc/init.d/sddm ]; then
                   	cp /usr/share/sddm-modified-defaults/sddm /etc/init.d/sddm
                   fi
                   update-rc.d sddm remove
                   update-rc.d sddm defaults
                   update-rc.d oosddm remove
                   #update-rc.d oosddm defaults
                   ;;

                *) :
                   ;;
esac 

exit 0
